language: python
python:
  - "2.6"
  - "2.7"
install:
before_script:
script:
  # Normal tests
  - python -m unittest discover
notifications:
  irc:
    channels: "irc.freenode.org#fabric"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false